platform :ios, '10.0'
use_frameworks!

target ‘宝贝时光’  do
pod 'MJRefresh'
pod 'MJExtension'
pod 'AFNetworking', '~> 3.0.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SDWebImage' #图片
pod 'IDMPhotoBrowser'#图片浏览器
end
